---
name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  wait-for-ci:
    name: Wait for CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI to pass
        uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: ${{ github.sha }}
          running-workflow-name: Wait for CI
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  publish:
    name: Publish Client
    needs: wait-for-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19'
          otp-version: '28'
      - name: Install Dependencies
        run: mix deps.get
      - name: Publish to Hex
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish --yes
